language: node_js
node_js:
  - '6.9.2'
branches:
  only:
  - master
  - dev
  - staging
  - production
  - "/.*(\\/)dev$/"
  - "/.*(\\/)staging$/"
  - "/.*(\\/)production$/"
notifications:
  slack: unity:4glShJwnSgraqabpTiqlEC6X
